pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/vijay2181/jenkins-pr-merge-on-success'
        CONTEXT = 'ci/jenkins/build-status'
        GITHUB_API_URL = 'https://api.github.com/repos/vijay2181/jenkins-pr-merge-on-success'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Use Jenkins environment variables for the branch name
                    def branchName = env.BRANCH_NAME
                    echo "Checking out branch: ${branchName}"
                    
                    // Checkout the branch
                    git url: "${REPO_URL}", branch: branchName
                }
            }
        }

        stage('Build Steps') {
            steps {
                script {
                    // Add your testing scripts here
                    echo "Pull Request Number: ${env.CHANGE_ID}"
                    echo "Pull Request Traget Branch: ${env.CHANGE_TARGET}"
                    echo "Pull Request Branch: ${env.BRANCH_NAME}"
                }
            }
        }
    }
}
